### ISSUE TITLE
PHP Notice when checking out with Virtual Product 

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-amazon-pay#13] opened 2020-06-12 15:18 UTC
When we purchase only a virtual product, WooCommerce skips the shipping calculation. If we then check out with Amazon Pay we will be redirected to the Checkout where we select only the Card and not the Shipping Address.

![image](https://user-images.githubusercontent.com/11388669/56744489-88c32800-6770-11e9-9a7a-4acaef2429e1.png)

This works fine when checking out but it generates the following notice:

```
[25-Apr-2019 14:04:00 UTC] PHP Notice:  Trying to get property 'Name' of non-object in wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-api.php on line 1679
[25-Apr-2019 14:04:00 UTC] PHP Stack trace:
[25-Apr-2019 14:04:00 UTC] PHP   3. require() index.php:17
[25-Apr-2019 14:04:00 UTC] PHP   4. require_once() wp-blog-header.php:19
[25-Apr-2019 14:04:00 UTC] PHP   5. do_action() wp-includes/template-loader.php:13
[25-Apr-2019 14:04:00 UTC] PHP   6. WP_Hook->do_action() wp-includes/plugin.php:465
[25-Apr-2019 14:04:00 UTC] PHP   7. WP_Hook->apply_filters() wp-includes/class-wp-hook.php:310
[25-Apr-2019 14:04:00 UTC] PHP   8. WC_AJAX::do_wc_ajax() wp-includes/class-wp-hook.php:286
[25-Apr-2019 14:04:00 UTC] PHP   9. do_action() wp-content/plugins/woocommerce/includes/class-wc-ajax.php:87
[25-Apr-2019 14:04:00 UTC] PHP  10. WP_Hook->do_action() wp-includes/plugin.php:465
[25-Apr-2019 14:04:00 UTC] PHP  11. WP_Hook->apply_filters() wp-includes/class-wp-hook.php:310
[25-Apr-2019 14:04:00 UTC] PHP  12. WC_AJAX::checkout() wp-includes/class-wp-hook.php:286
[25-Apr-2019 14:04:00 UTC] PHP  13. WC_Checkout->process_checkout() wp-content/plugins/woocommerce/includes/class-wc-ajax.php:462
[25-Apr-2019 14:04:00 UTC] PHP  14. WC_Checkout->process_order_payment() wp-content/plugins/woocommerce/includes/class-wc-checkout.php:1123
[25-Apr-2019 14:04:00 UTC] PHP  15. WC_Gateway_Amazon_Payments_Advanced->process_payment() wp-content/plugins/woocommerce/includes/class-wc-checkout.php:923
[25-Apr-2019 14:04:00 UTC] PHP  16. WC_Gateway_Amazon_Payments_Advanced->store_order_address_details() wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-gateway-amazon-payments-advanced.php:775
[25-Apr-2019 14:04:00 UTC] PHP  17. WC_Amazon_Payments_Advanced_API::format_address() wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-gateway-amazon-payments-advanced.php:1193
```

It's the following line which causes the notice: https://github.com/woocommerce/woocommerce-gateway-amazon-payments-advanced/blob/1.9.1/includes/class-wc-amazon-payments-advanced-api.php#L1679

If the server doesn't hide notices then it can cause the AJAX checkout request to fail.

Affected ticket: 1967059-zen

**Comment by alexiglesias31** [comment] 2023-12-01 09:47
Closing the ticket since the issue is not reproducible anymore.

**Closed by alexiglesias31** 2023-12-01 09:47 UTC
Labels: [Type] Bug, Priority: Low
