### ISSUE TITLE
Upgrade AutoKeyExchange/SimplePath URLs to HTTPS

### ISSUE THREAD

**Issue by jrodger** [woocommerce/woocommerce-gateway-amazon-pay#33] opened 2020-06-15 16:13 UTC
The credentials generated and passed over by Amazon Pay can only be sent to an HTTPS endpoint, however we see some cases where merchants are triggering the simple path/auto key exchange/onboarding workflow from an HTTP URL.

I see that the admin settings page uses [home_url](https://github.com/woocommerce/woocommerce-gateway-amazon-payments-advanced/blob/9f4ce0394fc1f49bb52ed69a97b1c4c0c98a1f6c/woocommerce-gateway-amazon-payments-advanced.php#L845) to determine where the credentials will be sent to. 

According to the [WordPress docs](https://developer.wordpress.org/reference/functions/get_home_url/), the scheme parameter could be set to HTTPS to enforce the HTTPS URLs.

**Comment by alexiglesias31** [comment] 2023-12-01 09:46
Closing the ticket since the issue is not reproducible anymore.

**Closed by alexiglesias31** 2023-12-01 09:46 UTC
Labels: [Type] Enhancement, [Type] Good First Change, Priority: Low
