### ISSUE TITLE
PHP 7.3/7.4 compatibility

### ISSUE THREAD

**Issue by GeoJunkie** [woocommerce/woocommerce-gateway-amazon-pay#61] opened 2020-08-26 20:23 UTC
**Describe the bug**

PHP compatibility is currently tested up to PHP 7.2

https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/d273f8ec26f82c08167f9d21608f0043919e828f/.travis.yml#L5-L8

There are errors that come from PHP 7.3 compatibility checks:

```
FILE: /app/public/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-simple-path-handler.php
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 8 ERRORS AFFECTING 7 LINES
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 230 | ERROR | Function mcrypt_decrypt() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 230 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 231 | ERROR | The constant "MCRYPT_RIJNDAEL_128" is deprecated since PHP 7.1 and removed since PHP 7.2
 234 | ERROR | The constant "MCRYPT_MODE_CBC" is deprecated since PHP 7.1 and removed since PHP 7.2
 306 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead
 308 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead
 309 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead
 312 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FILE: /app/public/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/compats/class-wc-amazon-payments-advanced-multi-currency.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 154 | WARNING | Global with anything other than bare variables is discouraged since PHP 7.0. Found ${$global_name}
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FILE: /app/public/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-ipn-handler.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 142 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead
 144 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead
 145 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead
 148 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

This was asked about in the forums: https://wordpress.org/support/topic/compatible-with-php-7-3-and-7-4/

**Expected behavior**
Compatibility should be updated with PHP 7.3 and 7.4 to align with WooCommerce

https://github.com/woocommerce/woocommerce/blob/25ab294e3e3eb782e97598aba784471a2225a193/.travis.yml#L16-L22

**Comment by richdacuban** [comment] 2021-01-14 16:29
** Describe the bug **

We are receiving automated compatibility warnings from WP VIP regarding the transition to php 7.4. The following are these reported errors (please note that I have replaced the URLs which originally linked to code in our private repo with links to the matching code in this repo):

>The following issues were found when scanning branch <code>master</code> for PHP compatibility issues in preparation for upgrade to PHP version 7.4: 
>* <b>Warning in plugins/woocommerce-gateway-amazon-payments-advanced/includes/compats/class-wc-amazon-payments-advanced-multi-currency.php</b>: Global with anything other than bare variables is discouraged since PHP 7.0. Found ${$global_name} https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/compats/class-wc-amazon-payments-advanced-multi-currency.php#L154

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-ipn-handler.php</b>: Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-ipn-handler.php#L142

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-ipn-handler.php</b>: Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-ipn-handler.php#L144

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-ipn-handler.php</b>: Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-ipn-handler.php#L145

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-ipn-handler.php</b>: Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-ipn-handler.php#L148

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-simple-path-handler.php</b>: Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-simple-path-handler.php#L230

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-simple-path-handler.php</b>: Function mcrypt_decrypt() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-simple-path-handler.php#L230

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-simple-path-handler.php</b>: The constant "MCRYPT_RIJNDAEL_128" is deprecated since PHP 7.1 and removed since PHP 7.2 https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-simple-path-handler.php#L231

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-simple-path-handler.php</b>: The constant "MCRYPT_MODE_CBC" is deprecated since PHP 7.1 and removed since PHP 7.2 https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-simple-path-handler.php#L234

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-simple-path-handler.php</b>: Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-simple-path-handler.php#L306

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-simple-path-handler.php</b>: Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-simple-path-handler.php#L308

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-simple-path-handler.php</b>: Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-simple-path-handler.php#L309

>* <b>Error in plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-simple-path-handler.php</b>: Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead https://github.com/woocommerce/woocommerce-gateway-amazon-pay/blob/73e3c23d87992b658c573114bc52d4600d097da8/includes/class-wc-amazon-payments-advanced-simple-path-handler.php#L312


 >Note that this is an automated report. We recommend that the issues noted here are looked into, as it will make the transition to the new PHP version easier.

**Comment by Pairfum-London** [comment] 2021-01-22 12:23
Dear @richdacuban and @GeoJunkie 

We really appreciate you looking into this.

Your Amazon Pay plugin is a great plugin for us that surprisingly many of our customer use and it is a pity that we can't use it currently while we await your update for its php 7.4 compatibility.

Many thanks for creating & maintaining an excellent plugin.

Pairfum London

**Comment by portalzine** [comment] 2021-02-16 12:29
Any news about this, as some sites wont be downgrading for a single plugin. The last update of the plugin is 6 months old and Wordpress is up to 5.6 already ;)

**Comment by kalessil** [comment] 2021-05-12 13:55
Folks, the scope of 2.0.0 release was focused on migrating to new UI/APIs. When it comes to compatibility, aligning with WooCommerce is a good point and we need to re-evaluate it. I'll check with colleagues about the topic next week.

**Comment by Pairfum-London** [comment] 2021-05-12 14:17
Dear @kalessil 

Many thanks for the update.

For your information, our site is a live production site: https://www.pairfum.com

We find that many of our customers liked using Amazon Pay but since our site now uses PHP 7.4, we can unfortunately no longer use this plugin, i.e. it doesn't work with PHP 7.4.

Hence, we would very much appreciate it, if you could create the compatibility.

Many thanks,

Pairfum London

**Comment by alexiglesias31** [comment] 2023-12-01 11:19
Closing the ticket since the issue is not reproducible anymore.

**Closed by alexiglesias31** 2023-12-01 11:19 UTC
