### ISSUE TITLE
Improve php unit test setup

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-amazon-pay#19] opened 2020-06-12 15:34 UTC
**Describe the bug**

PHP unit test setup requires a project folder to have a specific name `woocommerce-gateway-amazon-payments-advanced/` and relies on `woocommerce` folder to be available next to the project root [[#](https://github.com/woocommerce/woocommerce-gateway-amazon-payments-advanced/blob/9035a328a4657209812ed484d19f523fe6ee6b00/tests/phpunit/bootstrap.php#L9)]. This makes it hard to setup and run unit tests locally.

**To Reproduce**

1. Rename project dir to something custom.
2. Follow instructions in `tests/README.md` for php unit test.
3. Tests fail to bootstrap with an error similar to this:

`Warning: require(/Users/vbelolapotkov/WebDev/a8c/projects/woocommerce-gateway-amazon-payments-advanced/woocommerce-gateway-amazon-payments-advanced.php): failed to open stream: No such file or directory in /Users/vbelolapotkov/WebDev/a8c/projects/amazon-pgw/tests/phpunit/bootstrap.php on line 11`

**Expected behavior**

Unit tests setup and run should be easy and fast.
Alternative solution with pulling required dependencies with composer suggested in 166-GH-woocommerce-payments

**Comment by alexiglesias31** [comment] 2023-12-01 09:56
Closing the ticket since the issue is not reproducible anymore.

**Closed by alexiglesias31** 2023-12-01 09:56 UTC
Labels: [Type] Technical Debt
