### ISSUE TITLE
Endless Loop in Checkout

### ISSUE THREAD

**Issue by DalbertHab** [woocommerce/woocommerce-gateway-amazon-pay#47] opened 2020-06-29 06:58 UTC
**Describe the bug**
The checkout fragments are being loaded in an endless loop.

**To Reproduce**
1. Install Amazonpay & a plugin to enable "multi currency support" - we use Product Price based on Countries
2. Add a product to cart
3. Login with your Amazon Account
4. Proceed to checkout
5. The address fragment and the price fragment refreshes each other in an endless loop

**Expected behavior**
After selecting an address of your amazon account, refresh the prices once.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

See https://wordpress.org/support/topic/endless-loop-in-checkout/

**Env**
- WP: 5.4.2
- WC: 4.2
- Amazon Pay: 1.12.2
- Price based on Countries: 2.0.8

**Comment by jessLundie** [comment] 2020-07-23 17:43
We claim compatibility with [Price Based on Country](https://wordpress.org/plugins/woocommerce-product-price-based-on-countries/) in our documentation here: https://docs.woocommerce.com/document/amazon-payments-advanced/#section-5

Additional information from [forum thread](https://wordpress.org/support/topic/endless-loop-in-checkout/) - @DalbertHab reports the following: 

```
I checked the diffs between 1.11.1 and 1.12.2 and found the relevant line:

amazon-app-widgets.js – line 427 – onPaymentSelect: wcAmazonUpdateCheckoutAddresses

These line is added in 1.12.x and causes the infinite loop (function calls in post 1).
```

As a temporary workaround, rolling back to Amazon Pay 1.11.1 resolves this issue.

**Comment by alexiglesias31** [comment] 2023-12-01 11:30
Closing the ticket since the issue is not reproducible anymore.

**Closed by alexiglesias31** 2023-12-01 11:30 UTC
Labels: [Type] Bug, [Type] Compatibility
