### ISSUE TITLE
Disable Sign Up Now button if customer needs to authorize future payments

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-amazon-pay#7] opened 2020-06-12 15:10 UTC
When purchasing a subscription the user is presented with a check box "Use my selected payment method for future authorised purchases and payments to this merchant.".

If this isn't ticked and the customer clicks "Sign Up Now" they will receive an error message:

```
The BillingAgreementId C02-3331847-3508013 has constraints BuyerConsentNotSet and cannot be confirmed
```

If the customer ticks and then unticks the checkbox then the "Sign Up Now" button is disabled.

**To Reproduce**
1. Add a subscription product to your cart
2. Go to the checkout and login with Amazon Pay
3. Press the "Sign Up Now" button to see the error message
4. Tick then untick the authorize future payments checkbox
5. The "Sign Up Now" button is disabled and cannot be clicked until the checkbox is ticked again

**Expected behavior**
It would be nice if the button was disabled until the checkbox is ticked. Perhaps we need a message somewhere telling the user why. Or perhaps we should never disable the sign up button to keep the behavior consistent.

**Comment by dwainm** [comment] 2020-06-12 15:10
Also in Also reported in 16658010-HC

**Comment by alexiglesias31** [comment] 2023-12-01 09:56
Closing the ticket since the issue is not reproducible anymore.

**Closed by alexiglesias31** 2023-12-01 09:56 UTC
Labels: Priority: Low
